version: "3.8"

services:
  backend:
    build:
      context: ./arba-backend/venv # Assuming main.py and app are in this directory
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./arba-backend/venv:/app # Mount the entire `venv` folder to `/app`
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
    depends_on:
      - db

  frontend:
    build:
      context: ./arba-frontend/arba-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
